Sylius\Component\Core\Model\TaxRate:
    exclusion_policy: ALL
    xml_root_name: tax-rate
    properties:
        zone:
            expose: false
    relations:
        -   rel: self
            href:
                route: sylius_admin_api_tax_rate_show
                parameters:
                    code: expr(object.getCode())
        -   rel: zone
            href:
                route: sylius_admin_api_zone_show
                parameters:
                    code: expr(object.getZone().getCode())
        -   rel: category
            href:
                route: sylius_admin_api_tax_category_show
                parameters:
                    code: expr(object.getCategory().getCode())
